### ISSUE TITLE
Update version on PyPI

### ISSUE THREAD

**Issue by StevenMaude** [Nitron/pelican-alias#13]
Not a huge problem, but it would be nice; I'm having to `pip install` from GitHub, since the PyPI version doesn't have [this fix](https://github.com/Nitron/pelican-alias/commit/089c06051bab93d8064b36a88c30cddeab64e013).

Thanks for the plugin, by the way.

**Comment by Nitron** [comment]
Sorry about that, 1.1 is now uploaded to pypi.

**Comment by StevenMaude** [comment]
No problem; thanks for the quick fix.
